name: yaml_serializer
description: Helps you serialize your Maps into YAML
version: 0.0.10
homepage: https://gitjournal.io

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  yaml: ^3.1.0

dev_dependencies:
  test: ^1.9.4
  pedantic: ^1.9.0
