name: yaml_serializer
description: Helps you serialize your Maps into YAML
version: 0.0.7
homepage: https://gitjournal.io

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  yaml: ^2.2.1

dev_dependencies:
  test: ^1.9.4
  pedantic: ^1.9.0
