name: yaml_serializer
description: Helps you serialize your Maps into YAML
version: 0.0.11
homepage: https://gitjournal.io

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  yaml: ^3.1.0

dev_dependencies:
  test: ^1.16.8
  lints: ^1.0.1
  fast_immutable_collections: ^7.1.2
